# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =========== Copyright 2023 @ CAMEL-AI.org. All Rights Reserved. ===========
from dataclasses import dataclass
from typing import Any, Dict, Union

from wonderwall.social_platform.typing import ActionType


@dataclass
class ManualAction:
    r"""Manual predefined actions that need to be executed by certain agents.

    Args:
        action_type: The action to perform. Can be an ``ActionType`` enum value
            (for social media simulations) or a plain string (for generic
            simulations).
        action_args: The arguments to pass to the action.
    """
    action_type: Union[ActionType, str]
    action_args: Dict[str, Any]

    def init(self, action_type, action_args):
        self.action_type = action_type
        self.action_args = action_args


@dataclass
class LLMAction:
    r"""Represents actions generated by a Language Learning Model (LLM)."""

    def init(self):
        pass
